/*
 * Self-checking test suite for the LTRIM_ZERO collation.
 *
 * Every check writes one row into TST. A check of kind 'A' (assert) fails the
 * suite when ACTUAL differs from EXPECTED. A check of kind 'I' (info) only
 * records the observed behaviour and never fails: those are the documented
 * limits of the collation, not bugs.
 *
 * Run with:  isql -user SYSDBA -password masterkey -input test_ltrim_zero.sql
 * The suite passes when the final FAILED count is 0.
 */

SET NAMES UTF8;
SET SQL DIALECT 3;

CREATE DATABASE 'test_ltrim.fdb' PAGE_SIZE 8192 DEFAULT CHARACTER SET WIN1252;

/* External collations are not registered automatically. */
/* CASE INSENSITIVE is what makes SIMILAR TO consistent with LIKE and
   CONTAINING: SIMILAR TO is compiled to RE2 and reads the flag from the
   collation attributes instead of going through texttype_fn_canonical. */
CREATE COLLATION WIN1252_LTRIM_ZERO FOR WIN1252
    FROM EXTERNAL ('WIN1252_LTRIM_ZERO') CASE INSENSITIVE PAD SPACE;

CREATE COLLATION ISO8859_1_LTRIM_ZERO FOR ISO8859_1
    FROM EXTERNAL ('ISO8859_1_LTRIM_ZERO') CASE INSENSITIVE PAD SPACE;

/* Same driver, NO PAD, to prove texttype_pad_option is honoured. */
CREATE COLLATION WIN1252_LTZ_NOPAD FOR WIN1252
    FROM EXTERNAL ('WIN1252_LTRIM_ZERO') NO PAD;

COMMIT;

CREATE TABLE TST (
    SEQ   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    KIND  CHAR(1) DEFAULT 'A',
    NAME  VARCHAR(90),
    EXPECTED VARCHAR(80),
    ACTUAL   VARCHAR(80)
);

COMMIT;


/* ------------------------------------------------------------------ */
/* 0. The collations are installed                                     */
/* ------------------------------------------------------------------ */

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '0.1 both LTRIM_ZERO collations registered', '2',
       CAST((SELECT COUNT(*) FROM RDB$COLLATIONS
             WHERE RDB$COLLATION_NAME IN ('WIN1252_LTRIM_ZERO', 'ISO8859_1_LTRIM_ZERO')) AS VARCHAR(80))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* 1. VARCHAR: leading zeros / spaces and ASCII case are ignored       */
/* ------------------------------------------------------------------ */

CREATE TABLE T_VC (
    ID INTEGER,
    V  VARCHAR(20) CHARACTER SET WIN1252 COLLATE WIN1252_LTRIM_ZERO
);

INSERT INTO T_VC VALUES ( 1, '00000A');
INSERT INTO T_VC VALUES ( 2, '0A');
INSERT INTO T_VC VALUES ( 3, 'A');
INSERT INTO T_VC VALUES ( 4, '    A');
INSERT INTO T_VC VALUES ( 5, 'a');
INSERT INTO T_VC VALUES ( 6, '00000a');
INSERT INTO T_VC VALUES ( 7, '0 A 0');    /* trim stops at the first real character */
INSERT INTO T_VC VALUES ( 8, '00001');
INSERT INTO T_VC VALUES ( 9, '1');
INSERT INTO T_VC VALUES (10, '     1');
INSERT INTO T_VC VALUES (11, 'B');
INSERT INTO T_VC VALUES (12, '0000B');
INSERT INTO T_VC VALUES (13, 'A00');      /* trailing zeros are significant */
INSERT INTO T_VC VALUES (14, '00A00');
COMMIT;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '1.1 = ''A'' matches every leading-zero/space/case variant', '6',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V = 'A') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '1.2 = ''a'' gives the same set (case insensitive)', '6',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V = 'a') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '1.3 = ''0000000a'' gives the same set', '6',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V = '0000000a') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '1.4 = ''1'' matches the three numeric variants', '3',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V = '1') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '1.5 trailing zeros are significant: ''A00'' matches 2, not 8', '2',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V = 'A00') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '1.6 trim stops at the first real character: ''0 A 0'' is its own value', '1',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V = 'A 0') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '1.7 DISTINCT agrees with = (A, 1, B, A00, "A 0")', '5',
       CAST((SELECT COUNT(*) FROM (SELECT DISTINCT V FROM T_VC)) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '1.8 GROUP BY agrees with DISTINCT', '5',
       CAST((SELECT COUNT(*) FROM (SELECT V FROM T_VC GROUP BY V)) AS VARCHAR(80))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* 2. PAD SPACE: trailing spaces are ignored (this is what makes CHAR  */
/*    columns work at all)                                             */
/* ------------------------------------------------------------------ */

CREATE TABLE T_PAD (
    ID INTEGER,
    C  CHAR(8)     CHARACTER SET WIN1252 COLLATE WIN1252_LTRIM_ZERO,
    V  VARCHAR(20) CHARACTER SET WIN1252 COLLATE WIN1252_LTRIM_ZERO,
    N  VARCHAR(20) CHARACTER SET WIN1252 COLLATE WIN1252_LTZ_NOPAD
);

INSERT INTO T_PAD VALUES (1, 'A',     'A',     'A');
INSERT INTO T_PAD VALUES (2, '000A',  'A   ',  'A   ');
INSERT INTO T_PAD VALUES (3, '  a  ', '00a  ', '00a');
COMMIT;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '2.1 CHAR column: = ''A'' matches all 3 rows', '3',
       CAST((SELECT COUNT(*) FROM T_PAD WHERE C = 'A') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '2.2 CHAR compared to CHAR of the same value', '3',
       CAST((SELECT COUNT(*) FROM T_PAD WHERE C = CAST('0A' AS CHAR(8))) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '2.3 VARCHAR with trailing spaces = ''A'' (PAD SPACE)', '3',
       CAST((SELECT COUNT(*) FROM T_PAD WHERE V = 'A') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '2.4 CHAR to VARCHAR cross comparison', '3',
       CAST((SELECT COUNT(*) FROM T_PAD WHERE C = V) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '2.5 NO PAD variant keeps trailing spaces significant', '2',
       CAST((SELECT COUNT(*) FROM T_PAD WHERE N = 'A') AS VARCHAR(80))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* 3. Everything made only of zeros and spaces is one single class,    */
/*    equal to the empty string                                        */
/* ------------------------------------------------------------------ */

CREATE TABLE T_EMPTY (
    ID INTEGER,
    V  VARCHAR(10) CHARACTER SET WIN1252 COLLATE WIN1252_LTRIM_ZERO
);

INSERT INTO T_EMPTY VALUES (1, '000');
INSERT INTO T_EMPTY VALUES (2, '0');
INSERT INTO T_EMPTY VALUES (3, '   ');
INSERT INTO T_EMPTY VALUES (4, ' ');
INSERT INTO T_EMPTY VALUES (5, '0000 ');
INSERT INTO T_EMPTY VALUES (6, ' 0 ');
INSERT INTO T_EMPTY VALUES (7, '');
INSERT INTO T_EMPTY VALUES (8, NULL);
INSERT INTO T_EMPTY VALUES (9, '0A');
COMMIT;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '3.1 = ''0'' matches all 7 zero/space/empty rows', '7',
       CAST((SELECT COUNT(*) FROM T_EMPTY WHERE V = '0') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '3.2 = '''' gives exactly the same set', '7',
       CAST((SELECT COUNT(*) FROM T_EMPTY WHERE V = '') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '3.3 = ''   '' gives exactly the same set', '7',
       CAST((SELECT COUNT(*) FROM T_EMPTY WHERE V = '   ') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '3.4 NULL is not part of the class', '1',
       CAST((SELECT COUNT(*) FROM T_EMPTY WHERE V IS NULL) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '3.5 GROUP BY: empty class + ''A'' = 2 groups (NULL excluded)', '2',
       CAST((SELECT COUNT(*) FROM (SELECT V FROM T_EMPTY WHERE V IS NOT NULL GROUP BY V)) AS VARCHAR(80))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* 4. Index and natural scan must return the same rows                 */
/*    (compare() and string_to_key() agreement)                        */
/* ------------------------------------------------------------------ */

CREATE INDEX IX_VC_V   ON T_VC(V);
CREATE INDEX IX_PAD_C  ON T_PAD(C);
CREATE INDEX IX_EMPTY_V ON T_EMPTY(V);
COMMIT;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '4.1 T_VC = ''A'': index plan matches natural plan',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V = 'A' PLAN (T_VC NATURAL)) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM T_VC WHERE V = 'A' PLAN (T_VC INDEX (IX_VC_V))) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '4.2 T_VC = ''00001'': index plan matches natural plan',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V = '00001' PLAN (T_VC NATURAL)) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM T_VC WHERE V = '00001' PLAN (T_VC INDEX (IX_VC_V))) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '4.3 T_PAD CHAR = ''A'': index plan matches natural plan',
       CAST((SELECT COUNT(*) FROM T_PAD WHERE C = 'A' PLAN (T_PAD NATURAL)) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM T_PAD WHERE C = 'A' PLAN (T_PAD INDEX (IX_PAD_C))) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '4.4 T_EMPTY = ''0'': index plan matches natural plan',
       CAST((SELECT COUNT(*) FROM T_EMPTY WHERE V = '0' PLAN (T_EMPTY NATURAL)) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM T_EMPTY WHERE V = '0' PLAN (T_EMPTY INDEX (IX_EMPTY_V))) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '4.5 T_EMPTY = '''' (empty key): index plan matches natural plan',
       CAST((SELECT COUNT(*) FROM T_EMPTY WHERE V = '' PLAN (T_EMPTY NATURAL)) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM T_EMPTY WHERE V = '' PLAN (T_EMPTY INDEX (IX_EMPTY_V))) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '4.6 ORDER BY via explicit sort matches the default plan',
       (SELECT LIST(ID, ',') FROM (SELECT ID FROM T_VC PLAN SORT (T_VC NATURAL) ORDER BY V, ID)),
       (SELECT LIST(ID, ',') FROM (SELECT ID FROM T_VC ORDER BY V, ID))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '4.7 index range on the empty class is not wider than the natural scan',
       CAST((SELECT COUNT(*) FROM T_EMPTY WHERE V > '' PLAN (T_EMPTY NATURAL)) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM T_EMPTY WHERE V > '' PLAN (T_EMPTY INDEX (IX_EMPTY_V))) AS VARCHAR(80))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* 5. UNIQUE constraint follows the collation                          */
/* ------------------------------------------------------------------ */

CREATE TABLE T_UQ (
    V VARCHAR(20) CHARACTER SET WIN1252 UNIQUE COLLATE WIN1252_LTRIM_ZERO
);
COMMIT;

INSERT INTO T_UQ VALUES ('A');
COMMIT;

SET TERM ^ ;

EXECUTE BLOCK AS
DECLARE VIOLATED INTEGER = 0;
BEGIN
    BEGIN
        INSERT INTO T_UQ VALUES ('000a  ');
        WHEN ANY DO VIOLATED = 1;
    END
    INSERT INTO TST (NAME, EXPECTED, ACTUAL)
        VALUES ('5.1 ''000a  '' rejected as duplicate of ''A''', '1', CAST(:VIOLATED AS VARCHAR(80)));
END^

EXECUTE BLOCK AS
DECLARE VIOLATED INTEGER = 0;
BEGIN
    BEGIN
        INSERT INTO T_UQ VALUES ('B');
        WHEN ANY DO VIOLATED = 1;
    END
    INSERT INTO TST (NAME, EXPECTED, ACTUAL)
        VALUES ('5.2 ''B'' accepted (different class)', '0', CAST(:VIOLATED AS VARCHAR(80)));
END^

SET TERM ; ^

COMMIT;


/* ------------------------------------------------------------------ */
/* 6. Long strings: no size cap, no collapsing in sort / group by      */
/*    (the old driver refused anything over 32000 bytes and reported   */
/*    "equal", which made comparison intransitive)                     */
/* ------------------------------------------------------------------ */

CREATE TABLE T_LONG (
    ID INTEGER,
    V  VARCHAR(32700) CHARACTER SET WIN1252 COLLATE WIN1252_LTRIM_ZERO
);

/* _WIN1252 introducers: the connection charset is UTF8 and an UTF8 literal
   of 32600 characters would exceed the internal string size limit. */
INSERT INTO T_LONG VALUES (1, LPAD(_WIN1252 'A', 32600, _WIN1252 '0'));
INSERT INTO T_LONG VALUES (2, LPAD(_WIN1252 'B', 32600, _WIN1252 '0'));
INSERT INTO T_LONG VALUES (3, LPAD(_WIN1252 'A', 32500, _WIN1252 '0'));
COMMIT;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '6.0 the three long values were stored at full length', '32600,32600,32500',
       (SELECT LIST(CHAR_LENGTH(V), ',') FROM (SELECT ID, V FROM T_LONG ORDER BY ID))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '6.1 32600 byte value normalizes to ''A''', '2',
       CAST((SELECT COUNT(*) FROM T_LONG WHERE V = 'A') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '6.2 long ''A'' and long ''B'' are not equal', '0',
       CAST((SELECT COUNT(*) FROM T_LONG A JOIN T_LONG B ON A.V = B.V
             WHERE A.ID = 1 AND B.ID = 2) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '6.3 GROUP BY over long values gives 2 groups, not 1', '2',
       CAST((SELECT COUNT(*) FROM (SELECT V FROM T_LONG GROUP BY V)) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '6.4 long ''B'' is matched only by ''B''', '1',
       CAST((SELECT COUNT(*) FROM T_LONG WHERE V = 'B') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '6.5 ORDER BY over long values puts the two ''A'' rows first', '1,3,2',
       (SELECT LIST(ID, ',') FROM (SELECT ID FROM T_LONG ORDER BY V, ID))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* 6b. Values whose NORMALIZED form is longer than MAX_KEY (8192)      */
/*     Discriminating test: the same data is stored twice, once with   */
/*     LTRIM_ZERO and once with the default collation. Whatever the    */
/*     engine limit is, both columns must behave the same way. A       */
/*     difference between V and P would be a regression of this        */
/*     driver; identical behaviour is an engine wide limit.            */
/* ------------------------------------------------------------------ */

CREATE TABLE T_BIGKEY (
    ID INTEGER,
    V  VARCHAR(12000) CHARACTER SET WIN1252 COLLATE WIN1252_LTRIM_ZERO,
    P  VARCHAR(12000) CHARACTER SET WIN1252
);

/* Nothing is strippable: 11999 'X' then a single distinguishing byte,
   so the normalized key is 12000 bytes, well over MAX_KEY = 8192. */
INSERT INTO T_BIGKEY VALUES (1, LPAD(_WIN1252 'A', 12000, _WIN1252 'X'),
                                LPAD(_WIN1252 'A', 12000, _WIN1252 'X'));
INSERT INTO T_BIGKEY VALUES (2, LPAD(_WIN1252 'B', 12000, _WIN1252 'X'),
                                LPAD(_WIN1252 'B', 12000, _WIN1252 'X'));
COMMIT;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '6b.1 GROUP BY over 12000 byte keys: LTRIM_ZERO behaves like the default collation',
       CAST((SELECT COUNT(*) FROM (SELECT P FROM T_BIGKEY GROUP BY P)) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM (SELECT V FROM T_BIGKEY GROUP BY V)) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '6b.2 ORDER BY over 12000 byte keys: same order as the default collation',
       (SELECT LIST(ID, ',') FROM (SELECT ID FROM T_BIGKEY ORDER BY P)),
       (SELECT LIST(ID, ',') FROM (SELECT ID FROM T_BIGKEY ORDER BY V))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '6b.3 DISTINCT over 12000 byte keys matches the default collation',
       CAST((SELECT COUNT(*) FROM (SELECT DISTINCT P FROM T_BIGKEY)) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM (SELECT DISTINCT V FROM T_BIGKEY)) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '6b.4 = on 12000 byte values still discriminates (compare has no key limit)', '1',
       CAST((SELECT COUNT(*) FROM T_BIGKEY WHERE V = LPAD(_WIN1252 'B', 12000, _WIN1252 'X')) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (KIND, NAME, EXPECTED, ACTUAL)
SELECT 'I', '6b.5 how many groups the engine actually produces for 12000 byte keys', '2 if no limit',
       CAST((SELECT COUNT(*) FROM (SELECT V FROM T_BIGKEY GROUP BY V)) AS VARCHAR(80))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* 7. UPPER / LOWER keep the full charset case mapping (ICU),          */
/*    they must not degrade to ASCII only                              */
/* ------------------------------------------------------------------ */

CREATE TABLE T_CASE (
    ID INTEGER,
    V  VARCHAR(20) CHARACTER SET WIN1252 COLLATE WIN1252_LTRIM_ZERO
);

INSERT INTO T_CASE VALUES (1, 'ção');
INSERT INTO T_CASE VALUES (2, 'ÁÉÍÕÜ');
COMMIT;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '7.1 UPPER(''ção'') = ''ÇÃO'' (accents uppercased)', 'ÇÃO',
       (SELECT UPPER(V) FROM T_CASE WHERE ID = 1)
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '7.2 LOWER(''ÁÉÍÕÜ'') = ''áéíõü''', 'áéíõü',
       (SELECT LOWER(V) FROM T_CASE WHERE ID = 2)
FROM RDB$DATABASE;

INSERT INTO TST (KIND, NAME, EXPECTED, ACTUAL)
SELECT 'I', '7.3 comparison itself is ASCII-only: ''ção'' = ''ÇÃO'' is false', '0',
       CAST((SELECT COUNT(*) FROM T_CASE WHERE V = 'ÇÃO') AS VARCHAR(80))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* 8. Pattern matching. Canonical form is uppercase, so LIKE and         */
/*    CONTAINING are case-insensitive but NOT zero-insensitive.          */
/*    SIMILAR TO takes case insensitivity from the collation attribute.  */
/*    The 9 rows holding an 'A' are 1..7, 13 and 14.                     */
/* ------------------------------------------------------------------ */

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '8.1 LIKE is case-insensitive: LIKE ''%a%'' finds the uppercase rows', '9',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V LIKE '%a%') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '8.2 CONTAINING is case-insensitive', '9',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V CONTAINING 'a') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '8.3 SIMILAR TO is case-insensitive (needs CASE INSENSITIVE attribute)', '9',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V SIMILAR TO '%a%') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '8.4 LIKE ''A'' matches ''A'' and ''a'' only', '2',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V LIKE 'A') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (KIND, NAME, EXPECTED, ACTUAL)
SELECT 'I', '8.5 KNOWN LIMIT: LIKE is not zero-insensitive, ''00000A'' LIKE ''A'' is false', '2',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V LIKE 'A') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '8.6 STARTING WITH a fully strippable prefix agrees between plans',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V STARTING WITH '00' PLAN (T_VC NATURAL)) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM T_VC WHERE V STARTING WITH '00' PLAN (T_VC INDEX (IX_VC_V))) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '8.6b STARTING WITH ''00'': the index never loses a row',
       '5',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V STARTING WITH '00' PLAN (T_VC INDEX (IX_VC_V))) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '8.6c STARTING WITH a mixed case strippable prefix agrees between plans',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V STARTING WITH '0000' PLAN (T_VC NATURAL)) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM T_VC WHERE V STARTING WITH '0000' PLAN (T_VC INDEX (IX_VC_V))) AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '8.7 STARTING WITH a non strippable prefix agrees between plans',
       CAST((SELECT COUNT(*) FROM T_VC WHERE V STARTING WITH 'A' PLAN (T_VC NATURAL)) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM T_VC WHERE V STARTING WITH 'A' PLAN (T_VC INDEX (IX_VC_V))) AS VARCHAR(80))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* 9. Ordering is by codepoint of the normalized string, not numeric   */
/* ------------------------------------------------------------------ */

CREATE TABLE T_ORD (
    V VARCHAR(10) CHARACTER SET WIN1252 COLLATE WIN1252_LTRIM_ZERO
);

INSERT INTO T_ORD VALUES ('0009');
INSERT INTO T_ORD VALUES ('0010');
INSERT INTO T_ORD VALUES ('00100');
INSERT INTO T_ORD VALUES ('a');
INSERT INTO T_ORD VALUES ('B');
COMMIT;

INSERT INTO TST (KIND, NAME, EXPECTED, ACTUAL)
SELECT 'I', '9.1 KNOWN LIMIT: ordering is lexicographic, not numeric',
       '10,100,9,a,B',
       (SELECT LIST(TRIM(LEADING '0' FROM V), ',') FROM (SELECT V FROM T_ORD ORDER BY V))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* 10. ISO8859_1 registration works the same way                       */
/* ------------------------------------------------------------------ */

CREATE TABLE T_ISO (
    ID INTEGER,
    V  VARCHAR(20) CHARACTER SET ISO8859_1 COLLATE ISO8859_1_LTRIM_ZERO
);

INSERT INTO T_ISO VALUES (1, '00000123');
INSERT INTO T_ISO VALUES (2, '123');
INSERT INTO T_ISO VALUES (3, '   123');
INSERT INTO T_ISO VALUES (4, 'ABC');
INSERT INTO T_ISO VALUES (5, '000abc');
COMMIT;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '10.1 ISO8859_1: = ''123'' matches 3 rows', '3',
       CAST((SELECT COUNT(*) FROM T_ISO WHERE V = '123') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '10.2 ISO8859_1: = ''abc'' matches 2 rows', '2',
       CAST((SELECT COUNT(*) FROM T_ISO WHERE V = 'abc') AS VARCHAR(80))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* 11. Concurrency smoke test: the driver is stateless, so the same    */
/*     comparison repeated inside one big self join must stay stable   */
/* ------------------------------------------------------------------ */

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '11.1 self join over the equality class is stable (6 x 6)', '36',
       CAST((SELECT COUNT(*) FROM T_VC A JOIN T_VC B ON A.V = B.V
             WHERE A.V = 'A') AS VARCHAR(80))
FROM RDB$DATABASE;

INSERT INTO TST (NAME, EXPECTED, ACTUAL)
SELECT '11.2 hash join and index join agree',
       CAST((SELECT COUNT(*) FROM T_VC A JOIN T_VC B ON A.V = B.V) AS VARCHAR(80)),
       CAST((SELECT COUNT(*) FROM T_VC A JOIN T_VC B ON A.V = B.V
             PLAN JOIN (A NATURAL, B INDEX (IX_VC_V))) AS VARCHAR(80))
FROM RDB$DATABASE;

COMMIT;


/* ------------------------------------------------------------------ */
/* Report                                                              */
/* ------------------------------------------------------------------ */

SET WIDTH NAME 90;
SET WIDTH EXPECTED 30;
SET WIDTH ACTUAL 30;

SELECT '===== ALL CHECKS =====' AS REPORT FROM RDB$DATABASE;

SELECT SEQ, KIND, NAME, EXPECTED, ACTUAL,
       CASE WHEN KIND = 'I' THEN 'info'
            WHEN ACTUAL IS NOT DISTINCT FROM EXPECTED THEN 'PASS'
            ELSE 'FAIL' END AS RESULT
FROM TST
ORDER BY SEQ;

SELECT '===== FAILURES =====' AS REPORT FROM RDB$DATABASE;

SELECT SEQ, NAME, EXPECTED, ACTUAL
FROM TST
WHERE KIND = 'A' AND ACTUAL IS DISTINCT FROM EXPECTED
ORDER BY SEQ;

SELECT '===== SUMMARY =====' AS REPORT FROM RDB$DATABASE;

SELECT COUNT(*) AS TOTAL_ASSERTS,
       COUNT(*) FILTER (WHERE ACTUAL IS NOT DISTINCT FROM EXPECTED) AS PASSED,
       COUNT(*) FILTER (WHERE ACTUAL IS DISTINCT FROM EXPECTED) AS FAILED
FROM TST
WHERE KIND = 'A';

SELECT CASE WHEN EXISTS (SELECT 1 FROM TST WHERE KIND = 'A' AND ACTUAL IS DISTINCT FROM EXPECTED)
            THEN '*** SUITE FAILED ***'
            ELSE '*** SUITE PASSED ***' END AS VERDICT
FROM RDB$DATABASE;

COMMIT;
QUIT;
